set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm64)

if (NOT DEFINED POKY_INSTALL_DIR)
set(POKY_INSTALL_DIR "/opt/poky/2.1.3/")
endif()

if (NOT EXISTS ${POKY_INSTALL_DIR})
message(FATAL_ERROR "POKY_INSTALL_DIR \"${POKY_INSTALL_DIR}\": Does not exist")
endif()

message(STATUS "Use poky install directory ${POKY_INSTALL_DIR}")
set(SYSROOTS "${POKY_INSTALL_DIR}/sysroots/")
set(TARGET_PREFIX "aarch64-poky-linux-")

set(TOOLCHAIN_PREFIX ${SYSROOTS}/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/${TARGET_PREFIX})
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)

set(CMAKE_SYSROOT ${SYSROOTS}/aarch64-poky-linux/)

set(CMAKE_PREFIX_PATH ${CMAKE_SYSROOT}/usr/lib/cmake)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(COMPILER_FLAGS " -O2 -pipe -g -feliminate-unused-debug-types ")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${COMPILER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMPILER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CROSSCOMPILING "TRUE")
